services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      # image: "mcr.microsoft.com/devcontainers/universal:2"
    container_name: app

    security_opt:
      - apparmor=unconfined
    privileged: true

    volumes:
      - ..:/workspaces:cached
      - xtdb-logs:/workspaces/logs

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    depends_on:
      - xtdb

  xtdb:
    image: ghcr.io/xtdb/xtdb:edge
    container_name: xtdb
    restart: unless-stopped
    environment:
      JDK_JAVA_OPTIONS: "-Dlogback.configurationFile=/config/logback.xml"
      XTDB_LOGGING_LEVEL_PGWIRE: debug
    volumes:
      - xtdb-data:/var/lib/xtdb
      - ./xtdb.yaml:/config/xtdb.yaml
      - ./logback.xml:/config/logback.xml
      - xtdb-logs:/workspaces/logs
    command: ["-f", "/config/xtdb.yaml"]
    ports:
      - "5432:5432"  # Expose XTDB on the host

volumes:
  xtdb-data:
  xtdb-logs:
